name: Update

on:
  schedule:
    - cron:  '58 7 * * 3'
  workflow_dispatch:
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "bot@modm.io"
          git config --global user.name "modm update bot"
      - name: Update repository
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          wget -qL https://raw.githubusercontent.com/modm-ext/partial/main/partial.py
          python3 partial.py -v --head --dest CrashCatcher adamgreen/CrashCatcher README.creole include/CrashCatcher.h "Core/src/**/*"
          python3 partial.py -v --head --bin --dest CrashDebug adamgreen/CrashDebug README.creole "bins/**/*"
      - name: Test CrashDebug executable
        shell: python
        run: |
          import subprocess
          import sys
          p = subprocess.run("CrashDebug/bins/lin64/CrashDebug", capture_output=True)
          print(p.stderr)
          print("Return code: {}".format(p.returncode))
          if (p.returncode != 255) or ("CrashDebug - Cortex-M Post-Mortem Debugging" not in str(p.stderr)):
            print("Unexpected return code or stderr")
            sys.exit(1)
      - name: Git push
        if: github.ref == 'refs/heads/main'
        run: |
          git push origin main
